version: "3.9"
services: 
  gateway:
    build: "./server/api gateway"
    networks:
      - api
    ports: 
      - "80:80"
    volumes:
      - "./server/api gateway/nginx.conf:/etc/nginx/nginx.conf"
  db:
    image: "mysql:8.0"
    networks:
      - db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=blogdb
  auth:
    networks: 
      - api
      - db
    build: "./server/auth"
    volumes:
      - "./server/auth/index.js:/app/index.js"
  static:
    networks:
      - api
    build: "./server/static"
    environment:
      - "NODE_ENV=development"
networks:
  api:
  db: