POST http://localhost/api/device HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjgzMzYwNDAxfQ.-UDVtPbraOJ8RdRbkjROoFKeSZf8Lwx7uQQGs0X7C5s
Content-Type: application/json

{
    "name": "post long name",
    "description": "post long text",
}


# GET http://localhost/api/posts/51 HTTP/1.1
# Content-Type: none